In [2]:
import numpy as np

In [29]:
power = np.linspace(0,100,101)
array = np.array([0,1,2,3,4])
for a in power:
    numerator = np.power(array,a)
    denominator = np.sum(numerator)
    print(numerator/denominator)

[0.2 0.2 0.2 0.2 0.2]
[0.  0.1 0.2 0.3 0.4]
[0.         0.03333333 0.13333333 0.3        0.53333333]
[0.   0.01 0.08 0.27 0.64]
[0.         0.00282486 0.04519774 0.22881356 0.72316384]
[0.00000000e+00 7.69230769e-04 2.46153846e-02 1.86923077e-01
 7.87692308e-01]
[0.00000000e+00 2.04498978e-04 1.30879346e-02 1.49079755e-01
 8.37627812e-01]
[0.00000000e+00 5.34759358e-05 6.84491979e-03 1.16951872e-01
 8.76149733e-01]
[0.00000000e+00 1.38209360e-05 3.53815960e-03 9.06791608e-02
 9.05768859e-01]
[0.00000000e+00 3.54182900e-06 1.81341645e-03 6.97138202e-02
 9.28469222e-01]
[0.00000000e+00 9.01997925e-07 9.23645876e-04 5.32620755e-02
 9.45813377e-01]
[0.00000000e+00 2.28649823e-07 4.68274837e-04 4.05046302e-02
 9.59026866e-01]
[0.00000000e+00 5.77608854e-08 2.36588587e-04 3.06965027e-02
 9.69066851e-01]
[0.00000000e+00 1.45536300e-08 1.19223337e-04 2.32031870e-02
 9.76677575e-01]
[0.00000000e+00 3.65985578e-09 5.99630772e-05 1.75049768e-02
 9.82435056e-01]
[0.00000000e+00 9.19013329e-10 3.01